version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter-db
    restart: always
    environment:
      MYSQL_DATABASE: ci4
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      
    volumes:
      - ../volumes/mysql/data:/var/lib/mysql
      - ../volumes/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

volumes:
  mysql_data: